CREATE TABLE IF NOT EXISTS `#__error404` (
  `id_error404` int(11) NOT NULL auto_increment,
  `chaine` varchar(30) NOT NULL,
  `type` smallint(6) NOT NULL,
  PRIMARY KEY  (`id_error404`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

ALTER TABLE `#__error404` ADD UNIQUE (
`chaine`
);

CREATE TABLE IF NOT EXISTS `#__error404_stats` (
  `id_error404_stats` int(11) NOT NULL auto_increment,
  `referrer` varchar(150) NULL,
  `uri` varchar(100) NULL,
  `useragent` varchar(200) NULL,
  `ip` varchar(15) NULL,
  PRIMARY KEY  (`id_error404_stats`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='stats des erreurs 404' AUTO_INCREMENT=1 ;

INSERT IGNORE INTO `#__error404` (`id_error404`, `chaine`, `type`) VALUES
('', '/MSOffice/cl', 1),
('', '_vti_bin', 1),
('', 'anti_bot', 1),
('', 'Googlebot', 3),
('', 'favicon', 1),
('', 'msnbot', 3),
('', 'OrangeBot', 3),
('', 'crossdomain.xml', 1),
('', 'AdsBot-Google', 3),
('', 'robots.txt', 1),
('', 'MSOffice/cltreq.asp', 1),
('', 'ProxyJudge.cgi', 1),
('', ' ia_archiver', 3),
('', 'Scooter', 3),
('', 'Ask.Jeeves', 3),
('', 'Baiduspider', 3),
('', 'Exabot', 3),
('', 'FAST.Enterprise.Crawler', 3),
('', 'FAST-WebCrawler', 3),
('', 'www\\.neomo\\.de', 3),
('', 'Gigabot', 3),
('', 'Mediapartners-Google', 3),
('', 'Google.Desktop', 3),
('', 'Feedfetcher-Google', 3),
('', 'Googlebot|heise-IT-Markt-Crawl', 3),
('', 'heritrix', 3),
('', 'ibm.com\\cs/crawler', 3),
('', 'ICCrawler', 3),
('', 'ichiro', 3),
('', 'MJ12bot', 3),
('', 'MetagerBot', 3),
('', 'msnbot-NewsBlogs', 3),
('', 'msnbot-media', 3),
('', 'NG-Search', 3),
('', 'lucene.apache.org', 3),
('', 'NutchCVS', 3),
('', 'OmniExplorer_Bot', 3),
('', 'online.link.validator', 3),
('', 'psbot0', 3),
('', 'Seekbot', 3),
('', 'Sensis.Web.Crawler', 3),
('', 'SEO.search.Crawler', 3),
('', 'Seoma.\\[SEO.Crawler\\]', 3),
('', 'SEOsearch', 3),
('', 'Snappy', 3),
('', 'www.urltrends.com', 3),
('', 'www.tkl.iis.u-tokyo.ac.jp/~cra', 3),
('', 'SynooBot', 3),
('', 'crawleradmin.t-info@telekom.de', 3),
('', 'TurnitinBot', 3),
('', 'voyager', 3),
('', 'W3.SiteSearch.Crawler', 3),
('', 'W3C-checklink', 3),
('', 'W3C_Validator', 3),
('', 'www.WISEnutbot.com', 3),
('', 'yacybot', 3),
('', 'Yahoo-MMCrawler', 3),
('', 'Yahoo\\!.DE.Slurp', 3),
('', 'Yahoo\\!.Slurp', 3),
('', 'YahooSeeker', 3);
